services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"

  db:
    image: postgres:17
    ports:
      - "3002:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend-test

  backend:
    image: ghcr.io/marvell-consulting/statswales-backend:latest
    pull_policy: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      APP_ENV: 'ci'
      LOG_LEVEL: 'debug'
      TEST_DB_HOST: 'db'
      TEST_DB_PORT: 5432
