// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:lang/auth/login": {
    params: {
      "lang": string;
    };
  };
  "/:lang/auth/logout": {
    params: {
      "lang": string;
    };
  };
  "/:lang/auth/entraid": {
    params: {
      "lang": string;
    };
  };
  "/:lang/auth/callback": {
    params: {
      "lang": string;
    };
  };
  "/:lang": {
    params: {
      "lang": string;
    };
  };
  "/:lang/publish": {
    params: {
      "lang": string;
    };
  };
  "/:lang/publish/group": {
    params: {
      "lang": string;
    };
  };
  "/:lang/publish/title": {
    params: {
      "lang": string;
    };
  };
  "/:lang/publish/:datasetId/overview": {
    params: {
      "lang": string;
      "datasetId": string;
    };
  };
  "/:lang/publish/:datasetId/tasklist": {
    params: {
      "lang": string;
      "datasetId": string;
    };
  };
  "/:lang/publish/:datasetId/upload": {
    params: {
      "lang": string;
      "datasetId": string;
    };
  };
  "/:lang/publish/:datasetId/preview": {
    params: {
      "lang": string;
      "datasetId": string;
    };
  };
  "/:lang/publish/:datasetId/sources": {
    params: {
      "lang": string;
      "datasetId": string;
    };
  };
  "/:lang/admin": {
    params: {
      "lang": string;
    };
  };
  "/:lang/admin/group": {
    params: {
      "lang": string;
    };
  };
  "/:lang/admin/user": {
    params: {
      "lang": string;
    };
  };
  "/:lang/guidance": {
    params: {
      "lang": string;
    };
  };
  "/:lang/guidance/:doc": {
    params: {
      "lang": string;
      "doc": string;
    };
  };
  "/:lang/cookies": {
    params: {
      "lang": string;
    };
  };
  "/:lang/published/:datasetId": {
    params: {
      "lang": string;
      "datasetId": string;
    };
  };
  "/api/locales/:lng/:ns": {
    params: {
      "lng": string;
      "ns": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:lang/auth/login" | "/:lang/auth/logout" | "/:lang/auth/entraid" | "/:lang/auth/callback" | "/:lang" | "/:lang/publish" | "/:lang/publish/group" | "/:lang/publish/title" | "/:lang/publish/:datasetId/overview" | "/:lang/publish/:datasetId/tasklist" | "/:lang/publish/:datasetId/upload" | "/:lang/publish/:datasetId/preview" | "/:lang/publish/:datasetId/sources" | "/:lang/admin" | "/:lang/admin/group" | "/:lang/admin/user" | "/:lang/guidance" | "/:lang/guidance/:doc" | "/:lang/cookies" | "/:lang/published/:datasetId" | "/api/locales/:lng/:ns" | "/*";
  };
  "routes/layouts/publisher.tsx": {
    id: "routes/layouts/publisher";
    page: "/:lang/auth/login" | "/:lang/auth/logout" | "/:lang/auth/entraid" | "/:lang/auth/callback" | "/:lang" | "/:lang/publish" | "/:lang/publish/group" | "/:lang/publish/title" | "/:lang/publish/:datasetId/overview" | "/:lang/publish/:datasetId/tasklist" | "/:lang/publish/:datasetId/upload" | "/:lang/publish/:datasetId/preview" | "/:lang/publish/:datasetId/sources" | "/:lang/admin" | "/:lang/admin/group" | "/:lang/admin/user" | "/:lang/guidance" | "/:lang/guidance/:doc" | "/:lang/cookies";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/:lang/auth/login";
  };
  "routes/auth/logout.tsx": {
    id: "routes/auth/logout";
    page: "/:lang/auth/logout";
  };
  "routes/auth/entraid.ts": {
    id: "routes/auth/entraid";
    page: "/:lang/auth/entraid";
  };
  "routes/auth/callback.ts": {
    id: "routes/auth/callback";
    page: "/:lang/auth/callback";
  };
  "routes/auth/require-auth.tsx": {
    id: "routes/auth/require-auth";
    page: "/:lang" | "/:lang/publish" | "/:lang/publish/group" | "/:lang/publish/title" | "/:lang/publish/:datasetId/overview" | "/:lang/publish/:datasetId/tasklist" | "/:lang/publish/:datasetId/upload" | "/:lang/publish/:datasetId/preview" | "/:lang/publish/:datasetId/sources" | "/:lang/admin" | "/:lang/admin/group" | "/:lang/admin/user";
  };
  "routes/homepage.tsx": {
    id: "routes/homepage";
    page: "/:lang";
  };
  "routes/publish/start.tsx": {
    id: "routes/publish/start";
    page: "/:lang/publish";
  };
  "routes/publish/group.tsx": {
    id: "routes/publish/group";
    page: "/:lang/publish/group";
  };
  "routes/publish/title.tsx": {
    id: "routes/publish/title";
    page: "/:lang/publish/title";
  };
  "routes/publish/dataset/overview.tsx": {
    id: "routes/publish/dataset/overview";
    page: "/:lang/publish/:datasetId/overview";
  };
  "routes/publish/dataset/tasklist.tsx": {
    id: "routes/publish/dataset/tasklist";
    page: "/:lang/publish/:datasetId/tasklist";
  };
  "routes/publish/dataset/upload-dataset.tsx": {
    id: "routes/publish/dataset/upload-dataset";
    page: "/:lang/publish/:datasetId/upload";
  };
  "routes/publish/dataset/preview.tsx": {
    id: "routes/publish/dataset/preview";
    page: "/:lang/publish/:datasetId/preview";
  };
  "routes/publish/dataset/sources.tsx": {
    id: "routes/publish/dataset/sources";
    page: "/:lang/publish/:datasetId/sources";
  };
  "routes/admin/ensure-admin.tsx": {
    id: "routes/admin/ensure-admin";
    page: "/:lang/admin" | "/:lang/admin/group" | "/:lang/admin/user";
  };
  "routes/admin/groups/list.tsx": {
    id: "routes/admin/groups/list";
    page: "/:lang/admin/group";
  };
  "routes/admin/users/list.tsx": {
    id: "routes/admin/users/list";
    page: "/:lang/admin/user";
  };
  "routes/guidance/contents.tsx": {
    id: "routes/guidance/contents";
    page: "/:lang/guidance";
  };
  "routes/guidance/doc.tsx": {
    id: "routes/guidance/doc";
    page: "/:lang/guidance/:doc";
  };
  "routes/cookies.tsx": {
    id: "routes/cookies";
    page: "/:lang/cookies";
  };
  "routes/layouts/consumer.tsx": {
    id: "routes/layouts/consumer";
    page: "/:lang/published/:datasetId";
  };
  "routes/published/consumer-view.tsx": {
    id: "routes/published/consumer-view";
    page: "/:lang/published/:datasetId";
  };
  "routes/locales.ts": {
    id: "routes/locales";
    page: "/api/locales/:lng/:ns";
  };
  "routes/errors/not-found.tsx": {
    id: "routes/errors/not-found";
    page: "/*";
  };
};