# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Compose test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-version: 'latest'
        env:
          AZURE_DATALAKE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_DATALAKE_STORAGE_ACCOUNT_NAME }}
          AZURE_DATALAKE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_DATALAKE_STORAGE_ACCOUNT_KEY }}
          AZURE_DATALAKE_STORAGE_FILESYSTEM_NAME: ${{ secrets.AZURE_DATALAKE_STORAGE_FILESYSTEM_NAME }}
