# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run prettier:ci
      - run: npm run lint:ci
      - run: npm run build
      - run: npm run test:ci

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          compose-version: 'latest'

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          APP_ENV: ci
          FRONTEND_URL: http://localhost:3000
          BACKEND_URL: http://localhost:3001
          SESSION_STORE: memory
          SESSION_SECRET: peakaboo
          JWT_SECRET: jwtsecret
          SUPPORT_EMAIL: support@example.com
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright/results/
          retention-days: 30
